/**
 * ソムリンAI — ワインデータベース
 * 自動生成ファイル: update_wines.py で wines_import.csv から生成
 * 最終更新: 2026-06-13 | 件数: 137本
 *
 * ⚠️ このファイルを直接編集しないでください。
 *    wines_import.csv を更新後に update_wines.py を実行してください。
 */

// ワインデータ一覧
const wineDB = [
  {cat:'white',name:'カリフォルニア・ルーツ ピノ・グリージョ',producer:'トリンケロ・ファミリー・エステーツ',vintage:'2020',region:'アメリカ カリフォルニア',grapes:'ピノ・グリージョ',price:1380},
  {cat:'white',name:'カリフォルニア・ルーツ ソーヴィニヨン・ブラン',producer:'トリンケロ・ファミリー・エステーツ',vintage:'2020',region:'アメリカ カリフォルニア',grapes:'ソーヴィニヨン・ブラン',price:1380},
  {cat:'white',name:'ドライホップ ペット・ナット',producer:'フィールドレコーディングス',vintage:'',region:'アメリカ カリフォルニア セントラル・コースト',grapes:'シャルドネ',price:3500},
  {cat:'white',name:'カリフォルニア・ルーツ シャルドネ',producer:'トリンケロ・ファミリー・エステーツ',vintage:'2020',region:'アメリカ カリフォルニア',grapes:'シャルドネ',price:1380},
  {cat:'rose',name:'カリフォルニア・ルーツ ロゼ',producer:'トリンケロ・ファミリー・エステーツ',vintage:'2019',region:'アメリカ カリフォルニア',grapes:'ジンファンデル・シラー・メルロ他',price:1380},
  {cat:'red',name:'カリフォルニア・ルーツ カベルネ・ソーヴィニヨン',producer:'トリンケロ・ファミリー・エステーツ',vintage:'2019',region:'アメリカ カリフォルニア',grapes:'カベルネ・ソーヴィニヨン',price:1380},
  {cat:'white',name:'ティー・エヌ・ティー シャルドネ エステート・グロウン',producer:'オーク・リッジ・ワイナリー',vintage:'NV',region:'アメリカ カリフォルニア ローダイ',grapes:'シャルドネ',price:1400},
  {cat:'red',name:'ティー・エヌ・ティー ピノ・ノワール エステート・グロウン',producer:'オーク・リッジ・ワイナリー',vintage:'NV',region:'アメリカ カリフォルニア',grapes:'ピノ・ノワール',price:1400},
  {cat:'red',name:'ティー・エヌ・ティー ジンファンテル エステート・グロウン',producer:'オーク・リッジ・ワイナリー',vintage:'NV',region:'アメリカ カリフォルニア ローダイ',grapes:'ジンファンデル',price:1400},
  {cat:'red',name:'イントゥ カベルネ・ソーヴィニヨン',producer:'オーク・リッジ・ワイナリー',vintage:'2018',region:'アメリカ カリフォルニア ローダイ',grapes:'カベルネ・ソーヴィニヨン',price:1900},
  {cat:'red',name:'イントゥ ジンファンデル',producer:'オーク・リッジ・ワイナリー',vintage:'2017',region:'アメリカ カリフォルニア ローダイ',grapes:'ジンファンデル',price:1900},
  {cat:'rose',name:'オー・ジー・ヴィ ロゼ・オブ・プリミティーヴォ',producer:'オーク・リッジ・ワイナリー',vintage:'2019',region:'アメリカ カリフォルニア',grapes:'プリミティーボ',price:2300},
  {cat:'red',name:'オー・ジー・ヴィ オールド・ヴァイン・ジンファンデル',producer:'オーク・リッジ・ワイナリー',vintage:'2019',region:'アメリカ カリフォルニア ローダイ',grapes:'ジンファンデル',price:2300},
  {cat:'red',name:'オーク・リッジ リザーヴ エンシェント・ヴァイン・ジンファンデル',producer:'オーク・リッジ・ワイナリー',vintage:'2019',region:'アメリカ カリフォルニア ローダイ',grapes:'ジンファンデル',price:4250},
  {cat:'sparkling',name:'グローブ・ストリート・ワイナリー プライヴェート・キュヴェ スパークリング',producer:'ヴィンテージ・ワイン・エステーツ',vintage:'NV',region:'アメリカ カリフォルニア',grapes:'コロンバール主体',price:1850},
  {cat:'white',name:'クロ・ペガス シャルドネ ミツコズ・ヴィンヤード',producer:'ヴィンテージ・ワイン・エステーツ',vintage:'2019',region:'アメリカ カリフォルニア カーネロス ナパ・ヴァレー',grapes:'シャルドネ',price:5000},
  {cat:'red',name:'クロ・ペガス メルロ ミツコズ・ヴィンヤード',producer:'ヴィンテージ・ワイン・エステーツ',vintage:'2018',region:'アメリカ カリフォルニア カーネロス ナパ・ヴァレー',grapes:'メルロ',price:4800},
  {cat:'white',name:'ジラード シャルドネ',producer:'ヴィンテージ・ワイン・エステーツ',vintage:'2019',region:'アメリカ カリフォルニア ロス・カーネロス',grapes:'シャルドネ',price:3900},
  {cat:'red',name:'ジラード プティット・シラー',producer:'ヴィンテージ・ワイン・エステーツ',vintage:'2019',region:'アメリカ カリフォルニア ナパ・ヴァレー',grapes:'プティット・シラー',price:5400},
  {cat:'sparkling',name:'モン・ピエール ブリュット・キュヴェ スパークリング',producer:'ウェイベル・ヴィンヤーズ',vintage:'NV',region:'アメリカ カリフォルニア',grapes:'シュナン・ブラン・コロンバール',price:1380},
  {cat:'sparkling',name:'ブラン・ド・ノワール',producer:'シュラムスバーグ・ヴィンヤーズ',vintage:'2018',region:'アメリカ カリフォルニア ノース・コースト',grapes:'ピノ・ノワール',price:5300},
  {cat:'white',name:'コッポラ ロッソ&ビアンコ ピノ・グリージョ',producer:'フランシス・フォード・コッポラ・ワイナリー',vintage:'NV',region:'アメリカ カリフォルニア',grapes:'ピノ・グリ',price:1800},
  {cat:'red',name:'コッポラ ロッソ&ビアンコ ロッソ',producer:'フランシス・フォード・コッポラ・ワイナリー',vintage:'NV',region:'アメリカ カリフォルニア',grapes:'カベルネ・ジンファンデル・シラー他',price:1800},
  {cat:'sparkling',name:'フランシス・コッポラ ソフィア ブリュット・ロゼ',producer:'フランシス・フォード・コッポラ・ワイナリー',vintage:'NV',region:'アメリカ カリフォルニア モントレー',grapes:'非公開',price:3480},
  {cat:'rose',name:'フランシス・コッポラ ソフィア ロゼ',producer:'フランシス・フォード・コッポラ・ワイナリー',vintage:'2020',region:'アメリカ カリフォルニア モントレー',grapes:'グルナッシュ・シラー・ピノ他',price:3180},
  {cat:'white',name:'フランシス・コッポラ ダイヤモンド シャルドネ 250ml缶',producer:'フランシス・フォード・コッポラ・ワイナリー',vintage:'NV',region:'アメリカ カリフォルニア',grapes:'シャルドネ',price:750},
  {cat:'red',name:'フランシス・コッポラ ダイヤモンド ピノ・ノワール 250ml缶',producer:'フランシス・フォード・コッポラ・ワイナリー',vintage:'NV',region:'アメリカ カリフォルニア',grapes:'ピノ・ノワール',price:750},
  {cat:'red',name:'フランシス・フォード・コッポラ ディレクターズ・カット ジンファンデル',producer:'フランシス・フォード・コッポラ・ワイナリー',vintage:'2018',region:'アメリカ カリフォルニア ドライ・クリーク',grapes:'ジンファンデル',price:4480},
  {cat:'red',name:'フランシス・フォード・コッポラ ディレクターズ・カット カベルネ・ソーヴィニヨン',producer:'フランシス・フォード・コッポラ・ワイナリー',vintage:'2018',region:'アメリカ カリフォルニア アレクサンダー・ヴァレー',grapes:'カベルネ・ソーヴィニヨン',price:4271},
  {cat:'red',name:'ソーヴィニヨン・ブラン（イングルヌック）',producer:'イングルヌック',vintage:'2018',region:'アメリカ カリフォルニア ラザフォード',grapes:'ソーヴィニヨン・ブラン',price:6800},
  {cat:'white',name:'ファースト・プレス シャルドネ',producer:'デリカート・ファミリー・ワインズ',vintage:'2019',region:'アメリカ カリフォルニア ナパ・ヴァレー',grapes:'シャルドネ',price:3800},
  {cat:'white',name:'シャルドネ エステート・グロウン',producer:'ガーギッチ・ヒルズ・エステート',vintage:'2019',region:'アメリカ カリフォルニア ナパ・ヴァレー',grapes:'シャルドネ',price:7600},
  {cat:'white',name:'ソーヴィニヨン・ブラン エステート・グロウン ミラー・ランチ',producer:'シルヴァラード・ヴィンヤーズ',vintage:'2018',region:'アメリカ カリフォルニア ヨントヴィル',grapes:'ソーヴィニヨン・ブラン',price:3300},
  {cat:'red',name:'メルロ エステート・グロウン マウント・ジョージ・ヴィンヤード',producer:'シルヴァラード・ヴィンヤーズ',vintage:'2017',region:'アメリカ カリフォルニア クームスヴィル',grapes:'メルロ',price:5900},
  {cat:'red',name:'カベルネ・ソーヴィニヨン（スコット）',producer:'スコット・ファミリー・セラーズ',vintage:'2017',region:'アメリカ カリフォルニア',grapes:'カベルネ・ソーヴィニヨン',price:2020},
  {cat:'red',name:'カベルネ・ソーヴィニヨン（ホール）',producer:'ホール・ワインズ',vintage:'2018',region:'アメリカ カリフォルニア ナパ・ヴァレー',grapes:'カベルネ・ソーヴィニヨン',price:9000},
  {cat:'white',name:'涼風 シャルドネ',producer:'フリーマン・ヴィンヤード&ワイナリー',vintage:'2018',region:'アメリカ カリフォルニア グリーン・ヴァレー',grapes:'シャルドネ',price:7400},
  {cat:'red',name:'ピノ・ノワール（フリーマン）',producer:'フリーマン・ヴィンヤード&ワイナリー',vintage:'2018',region:'アメリカ カリフォルニア ソノマ・コースト',grapes:'ピノ・ノワール',price:7700},
  {cat:'red',name:'ユーキ・エステート ピノ・ノワール',producer:'フリーマン・ヴィンヤード&ワイナリー',vintage:'2018',region:'アメリカ カリフォルニア ソノマ・コースト',grapes:'ピノ・ノワール',price:10500},
  {cat:'red',name:'ジンファンデル（セバスチャーニ）',producer:'セバスチャーニ・ヴィンヤーズ&ワイナリー',vintage:'2017',region:'アメリカ カリフォルニア ノース・コースト',grapes:'ジンファンデル',price:2800},
  {cat:'white',name:'シャルドネ（ポール・ホブス）',producer:'ポール・ホブス・ワイナリー',vintage:'2019',region:'アメリカ カリフォルニア ロシアン・リヴァー・ヴァレー',grapes:'シャルドネ',price:7500},
  {cat:'white',name:'ハーン シャルドネ',producer:'ハーン・ファミリー・ワインズ',vintage:'2020',region:'アメリカ カリフォルニア',grapes:'シャルドネ',price:2450},
  {cat:'red',name:'ハーン ピノ・ノワール',producer:'ハーン・ファミリー・ワインズ',vintage:'2020',region:'アメリカ カリフォルニア',grapes:'ピノ・ノワール',price:2450},
  {cat:'red',name:'ハーン・ワイナリー ピノ・ノワール SLH エステート',producer:'ハーン・ファミリー・ワインズ',vintage:'2018',region:'アメリカ カリフォルニア サンタ・ルシア・ハイランズ',grapes:'ピノ・ノワール',price:4600},
  {cat:'red',name:'スミス&フック カベルネ・ソーヴィニヨン',producer:'ハーン・ファミリー・ワインズ',vintage:'2019',region:'アメリカ カリフォルニア セントラル・コースト',grapes:'カベルネ・ソーヴィニヨン',price:4700},
  {cat:'red',name:'シラー（ザ・ペアリング）',producer:'ザ・ペアリング',vintage:'2019',region:'アメリカ カリフォルニア サンタ・イネズ',grapes:'シラー',price:3500},
  {cat:'red',name:'レッド・カリフォルニア（ザ・ペアリング）',producer:'ザ・ペアリング',vintage:'2017',region:'アメリカ カリフォルニア',grapes:'カベルネ・ソーヴィニヨン・メルロ・カベルネ・フラン他',price:3500},
  {cat:'white',name:'シャルドネ エステート（ザ・ヒルト）',producer:'ザ・ヒルト',vintage:'2018',region:'アメリカ カリフォルニア サンタ・リタ・ヒルズ',grapes:'シャルドネ',price:5900},
  {cat:'red',name:'ピノ・ノワール エステート（ザ・ヒルト）',producer:'ザ・ヒルト',vintage:'2018',region:'アメリカ カリフォルニア サンタ・リタ・ヒルズ',grapes:'ピノ・ノワール',price:5900},
  {cat:'red',name:'スモーキング・ルーン カベルネ・ソーヴィニヨン',producer:'ドン・セバスチャーニ&サンズ',vintage:'NV',region:'アメリカ カリフォルニア',grapes:'カベルネ・ソーヴィニヨン',price:1780},
  {cat:'red',name:'コルク・ダンサー ピノ・ノワール',producer:'ヒッチング・ポスト',vintage:'2018',region:'アメリカ カリフォルニア サンタ・バーバラ',grapes:'ピノ・ノワール',price:5000},
  {cat:'white',name:'ベンド シャルドネ',producer:'フィオール・ディ・ソル',vintage:'2019',region:'アメリカ カリフォルニア',grapes:'シャルドネ',price:1000},
  {cat:'red',name:'ベンド カベルネ・ソーヴィニヨン',producer:'フィオール・ディ・ソル',vintage:'2020',region:'アメリカ カリフォルニア',grapes:'カベルネ・ソーヴィニヨン',price:1000},
  {cat:'white',name:'トゥウェンティ・ロウズ シャルドネ',producer:'フィオール・ディ・ソル',vintage:'2020',region:'アメリカ カリフォルニア ナパ・ヴァレー',grapes:'シャルドネ',price:2700},
  {cat:'red',name:'トゥウェンティ・ロウズ リザーヴ カベルネ・ソーヴィニヨン',producer:'フィオール・ディ・ソル',vintage:'2020',region:'アメリカ カリフォルニア ナパ・ヴァレー',grapes:'カベルネ・ソーヴィニヨン',price:3700},
  {cat:'white',name:'ペッパーウッド・グローヴ シャルドネ',producer:'ドン・セバスチャーニ&サンズ',vintage:'2018',region:'アメリカ カリフォルニア',grapes:'シャルドネ',price:1580},
  {cat:'red',name:'ペッパーウッド・グローヴ カベルネ・ソーヴィニヨン',producer:'ドン・セバスチャーニ&サンズ',vintage:'NV',region:'アメリカ カリフォルニア',grapes:'カベルネ・ソーヴィニヨン',price:1580},
  {cat:'white',name:'スモーキング・ルーン ソーヴィニヨン・ブラン',producer:'ドン・セバスチャーニ&サンズ',vintage:'2019',region:'アメリカ カリフォルニア',grapes:'ソーヴィニヨン・ブラン',price:1780},
  {cat:'rose',name:'スモーキング・ルーン スティールバード ロゼ',producer:'ドン・セバスチャーニ&サンズ',vintage:'2018',region:'アメリカ カリフォルニア',grapes:'バルベラ・シラー・グルナッシュ',price:1780},
  {cat:'white',name:'サイクルズ・グラディエーター ソーヴィニヨン・ブラン',producer:'ワイン・フーリガンズ',vintage:'2020',region:'アメリカ カリフォルニア',grapes:'ソーヴィニヨン・ブラン',price:1850},
  {cat:'red',name:'サイクルズ・グラディエーター ピノ・ノワール',producer:'ワイン・フーリガンズ',vintage:'2019',region:'アメリカ カリフォルニア',grapes:'ピノ・ノワール',price:1850},
  {cat:'red',name:'サイクルズ・グラディエーター メルロ',producer:'ワイン・フーリガンズ',vintage:'2019',region:'アメリカ カリフォルニア',grapes:'メルロ',price:1850},
  {cat:'white',name:'スタインヒューゲル リースリング',producer:'タトーマー',vintage:'2019',region:'アメリカ カリフォルニア サンタ・ルシア・ハイランズ',grapes:'リースリング',price:2950},
  {cat:'white',name:'ラ・マレーア アルバリーニョ クリスティ・ヴィンヤード',producer:'アイ.ブランド&ファミリー',vintage:'2020',region:'アメリカ カリフォルニア モントレー',grapes:'アルバリーニョ',price:3800},
  {cat:'red',name:'ル・プティ・ペイザン オールド・ヴァインズ カベルネ・ソーヴィニヨン',producer:'アイ.ブランド&ファミリー',vintage:'2019',region:'アメリカ カリフォルニア サン・ベニート',grapes:'カベルネ・ソーヴィニヨン',price:3300},
  {cat:'red',name:'シラー（アルノー・ロバーツ）',producer:'アルノー・ロバーツ',vintage:'2018',region:'アメリカ カリフォルニア ソノマ・コースト',grapes:'シラー',price:6200},
  {cat:'white',name:'シャルドネ（フェイラ）',producer:'フェイラ・ワインズ',vintage:'2018',region:'アメリカ カリフォルニア ソノマ・コースト',grapes:'シャルドネ',price:5950},
  {cat:'red',name:'ピノ・ノワール（フェイラ）',producer:'フェイラ・ワインズ',vintage:'2019',region:'アメリカ カリフォルニア ソノマ・コースト',grapes:'ピノ・ノワール',price:5950},
  {cat:'red',name:'ジンファンデル（デイ）',producer:'デイ',vintage:'2017',region:'アメリカ カリフォルニア ソノマ・カウンティ',grapes:'ジンファンデル',price:4900},
  {cat:'red',name:'カベルネ・ソーヴィニヨン ヴィレッジ No.3',producer:'マサイアソン・ファミリー・ヴィンヤード',vintage:'2019',region:'アメリカ カリフォルニア ナパ・ヴァレー',grapes:'カベルネ・ソーヴィニヨン',price:5800},
  {cat:'red',name:'モンキー・ジャケット レッド・ブレンド',producer:'クルーズ・ワイン・カンパニー',vintage:'2019',region:'アメリカ カリフォルニア ノース・コースト',grapes:'ヴァルディギエ・プティシラー・カリニャン他',price:3900},
  {cat:'red',name:'ジンファンデル スタンピード',producer:'メートル・ド・シェ',vintage:'2018',region:'アメリカ カリフォルニア ローダイ',grapes:'ジンファンデル',price:3900},
  {cat:'white',name:'ソーヴィニョンブラン（サニー）',producer:'サニー ウィズ ア チャンス オブ フラワーズ',vintage:'2020',region:'アメリカ カリフォルニア モントレー',grapes:'ソーヴィニヨン・ブラン',price:1773},
  {cat:'white',name:'シャルドネ（サニー）',producer:'サニー ウィズ ア チャンス オブ フラワーズ',vintage:'2019',region:'アメリカ カリフォルニア モントレー',grapes:'シャルドネ',price:1773},
  {cat:'white',name:'シャルドネ（ランチ32）',producer:'ランチ 32',vintage:'2019',region:'アメリカ カリフォルニア アローヨ・セコ',grapes:'シャルドネ',price:1618},
  {cat:'white',name:'シャルドネ（キャノンボール）',producer:'キャノンボール',vintage:'2019',region:'アメリカ カリフォルニア',grapes:'シャルドネ',price:2636},
  {cat:'white',name:'シャルドネ ソノマ コースト（チョーク ヒル）',producer:'チョーク ヒル',vintage:'2019',region:'アメリカ カリフォルニア ソノマ・コースト',grapes:'シャルドネ',price:3545},
  {cat:'white',name:'シャルドネ（ボーグル）',producer:'ボーグル ヴィンヤーズ',vintage:'2020',region:'アメリカ カリフォルニア',grapes:'シャルドネ',price:2045},
  {cat:'white',name:'シャルドネ サンタ ルチア ハイランズ（シャイド）',producer:'シャイド ヴィンヤーズ',vintage:'2017',region:'アメリカ カリフォルニア サンタ・ルチア・ハイランズ',grapes:'シャルドネ',price:5000},
  {cat:'white',name:'エステート ソーヴィニヨンブラン（チョーク ヒル）',producer:'チョーク ヒル',vintage:'2018',region:'アメリカ カリフォルニア チョーク・ヒル',grapes:'ソーヴィニヨン・ブラン',price:3818},
  {cat:'white',name:'ゲヴュルツトラミネール（ハイヴ&ハニー）',producer:'ハイヴ&ハニー',vintage:'2020',region:'アメリカ カリフォルニア モントレー',grapes:'ゲヴュルツトラミネール',price:1800},
  {cat:'red',name:'ピノノワール（サニー）',producer:'サニー ウィズ ア チャンス オブ フラワーズ',vintage:'2019',region:'アメリカ カリフォルニア モントレー',grapes:'ピノ・ノワール',price:1773},
  {cat:'red',name:'ピノノワール ソノマ コースト（チョーク ヒル）',producer:'チョーク ヒル',vintage:'2018',region:'アメリカ カリフォルニア ソノマ・コースト',grapes:'ピノ・ノワール',price:3727},
  {cat:'red',name:'ピノノワール（シャイド）',producer:'シャイド ヴィンヤーズ',vintage:'2018',region:'アメリカ カリフォルニア モントレー',grapes:'ピノ・ノワール',price:3818},
  {cat:'red',name:'ピノノワール サンタルチア ハイランズ（シャイド）',producer:'シャイド ヴィンヤーズ',vintage:'2016',region:'アメリカ カリフォルニア サンタ・ルチア・ハイランズ',grapes:'ピノ・ノワール',price:6273},
  {cat:'red',name:'メルロ（キャノンボール）',producer:'キャノンボール',vintage:'2019',region:'アメリカ カリフォルニア',grapes:'メルロ',price:2636},
  {cat:'red',name:'カベルネソーヴィニヨン（ランチ32）',producer:'ランチ 32',vintage:'2019',region:'アメリカ カリフォルニア モントレー',grapes:'カベルネ・ソーヴィニヨン',price:1618},
  {cat:'red',name:'カベルネソーヴィニヨン（キャノンボール）',producer:'キャノンボール',vintage:'2018',region:'アメリカ カリフォルニア',grapes:'カベルネ・ソーヴィニヨン',price:2636},
  {cat:'red',name:'カベルネソーヴィニヨン（ボーグル）',producer:'ボーグル ヴィンヤーズ',vintage:'2019',region:'アメリカ カリフォルニア',grapes:'カベルネ・ソーヴィニヨン',price:2255},
  {cat:'red',name:'レッド ブレンド（オッド ロット）',producer:'オッド ロット',vintage:'2019',region:'アメリカ カリフォルニア モントレー',grapes:'プティ・シラー・プティ・ヴェルド',price:2455},
  {cat:'red',name:'シラー カベルネ（オッド ロット）',producer:'オッド ロット',vintage:'2019',region:'アメリカ カリフォルニア モントレー',grapes:'シラー・カベルネ・ソーヴィニヨン',price:2455},
  {cat:'red',name:'レヴェレンス（ボーグル）',producer:'ボーグル ヴィンヤーズ',vintage:'2017',region:'アメリカ カリフォルニア',grapes:'カベルネ・マルベック・メルロ',price:4091},
  {cat:'red',name:'ジンファンデル（ザ スペシャリスト）',producer:'ザ スペシャリスト',vintage:'2018',region:'アメリカ カリフォルニア ローダイ',grapes:'ジンファンデル・プティ・シラー',price:2000},
  {cat:'red',name:'カベルネソーヴィニヨン カーツ ヴィンヤード',producer:'シャイド ヴィンヤーズ',vintage:'2016',region:'アメリカ カリフォルニア サン・ルーカス',grapes:'カベルネ・ソーヴィニヨン',price:8182},
  {cat:'red',name:'ハイ ダイブ ナパヴァレー',producer:'ハイ ダイブ',vintage:'2015',region:'アメリカ カリフォルニア ナパ・ヴァレー',grapes:'カベルネ・ソーヴィニヨン・メルロ・カベルネ・フラン他',price:17273},
  {cat:'sparkling',name:'Crémant du Jura Brut Lapiaz',producer:'Tissot-Maire',vintage:'',region:'フランス ジュラ',grapes:'ピノ・ノワール・シャルドネ',price:3000},
  {cat:'sparkling',name:'Crémant du Jura Blanc de Blancs Brut',producer:'Tissot-Maire',vintage:'',region:'フランス ジュラ',grapes:'ピノ・ノワール・トゥルソー・ブルサール',price:3500},
  {cat:'sparkling',name:'Crémant du Jura Blanc de Noirs Brut',producer:'Tissot-Maire',vintage:'',region:'フランス ジュラ',grapes:'シャルドネ',price:3500},
  {cat:'sparkling',name:'Crémant du Jura Brut Rosé',producer:'Tissot-Maire',vintage:'',region:'フランス ジュラ',grapes:'ピノ・ノワール',price:3500},
  {cat:'sparkling',name:'Crémant du Jura Millesim',producer:'Tissot-Maire',vintage:'2015',region:'フランス ジュラ',grapes:'シャルドネ',price:4000},
  {cat:'sparkling',name:'Riesling Sekt Brut Goldene Kapsel',producer:'Schloss Reinhartshausen',vintage:'',region:'ドイツ ラインガウ',grapes:'リースリング',price:5000},
  {cat:'sparkling',name:'Marcobrunn Riesling Sekt Extra Brut',producer:'Schloss Reinhartshausen',vintage:'2012',region:'ドイツ ラインガウ',grapes:'リースリング',price:8500},
  {cat:'sparkling',name:'Chardonnay Sekt Extra Brut',producer:'Schloss Reinhartshausen',vintage:'2015',region:'ドイツ ラインガウ',grapes:'シャルドネ',price:7000},
  {cat:'sparkling',name:'Pinot Rosee Sekt Brut',producer:'Schloss Reinhartshausen',vintage:'',region:'ドイツ ラインガウ',grapes:'ピノ・ムニエ・シュペートブルグンダー',price:5000},
  {cat:'white',name:'Riesling Kabinett feinherb',producer:'Schloss Reinhartshausen',vintage:'2020',region:'ドイツ ラインガウ',grapes:'リースリング',price:3300},
  {cat:'white',name:'Wisselbrunen Riesling Kabinett feinherb',producer:'Schloss Reinhartshausen',vintage:'2018',region:'ドイツ ラインガウ',grapes:'リースリング',price:5000},
  {cat:'white',name:'Hohenrain Riesling Alte Reben',producer:'Schloss Reinhartshausen',vintage:'2018',region:'ドイツ ラインガウ',grapes:'リースリング',price:5500},
  {cat:'white',name:'Marcobrunn Riesling Spätlese',producer:'Schloss Reinhartshausen',vintage:'2018',region:'ドイツ ラインガウ',grapes:'リースリング',price:10000},
  {cat:'white',name:'Schlossberg Monopol Riesling trocken',producer:'Schloss Reinhartshausen',vintage:'2015',region:'ドイツ ラインガウ',grapes:'リースリング',price:14000},
  {cat:'red',name:'Spätburgunder trocken',producer:'Schloss Reinhartshausen',vintage:'2018',region:'ドイツ ラインガウ',grapes:'シュペートブルグンダー',price:3500},
  {cat:'white',name:'Père et Fils Givry Blanc',producer:'Domaine Mouton',vintage:'2020',region:'フランス ブルゴーニュ',grapes:'シャルドネ',price:4500},
  {cat:'red',name:'Père et Fils Coteaux Bourguignons Les Fourneaux Rouge',producer:'Domaine Mouton',vintage:'2020',region:'フランス ブルゴーニュ',grapes:'ピノ・ノワール',price:3300},
  {cat:'red',name:'Père et Fils Givry Rouge',producer:'Domaine Mouton',vintage:'2020',region:'フランス ブルゴーニュ',grapes:'ピノ・ノワール',price:4500},
  {cat:'red',name:'Père et Fils Givry 1er cru Clos Charlé',producer:'Domaine Mouton',vintage:'2019',region:'フランス ブルゴーニュ',grapes:'ピノ・ノワール',price:5500},
  {cat:'red',name:'Père et Fils Givry 1er cru Les Grands Prélans',producer:'Domaine Mouton',vintage:'2019',region:'フランス ブルゴーニュ',grapes:'ピノ・ノワール',price:6000},
  {cat:'red',name:'Père et Fils Givry 1er cru La Grande Berge',producer:'Domaine Mouton',vintage:'2018',region:'フランス ブルゴーニュ',grapes:'ピノ・ノワール',price:5500},
  {cat:'red',name:"Joillot Bourgogne Côte d'Or Pinot Noir",producer:'Domaine Georges',vintage:'2019',region:'フランス ブルゴーニュ',grapes:'ピノ・ノワール',price:4000},
  {cat:'red',name:'Joillot Bourgogne Haute-Côtes de Beaune Rouge',producer:'Domaine Georges',vintage:'2019',region:'フランス ブルゴーニュ',grapes:'ピノ・ノワール',price:4500},
  {cat:'red',name:'Joillot Pommard Vielles Vignes',producer:'Domaine Georges',vintage:'2019',region:'フランス ブルゴーニュ',grapes:'ピノ・ノワール',price:8000},
  {cat:'red',name:'Joillot Pommard Les Nozions',producer:'Domaine Georges',vintage:'2019',region:'フランス ブルゴーニュ',grapes:'ピノ・ノワール',price:9000},
  {cat:'red',name:'Joillot Pommard 1er cru Les Charmots',producer:'Domaine Georges',vintage:'2019',region:'フランス ブルゴーニュ',grapes:'ピノ・ノワール',price:12500},
  {cat:'white',name:'Alex Gambal Bourgogne Chardonnay',producer:'Alex Gambal',vintage:'2019',region:'フランス ブルゴーニュ',grapes:'シャルドネ',price:5000},
  {cat:'white',name:'Alex Gambal Corton-Charlemagne',producer:'Alex Gambal',vintage:'2018',region:'フランス ブルゴーニュ',grapes:'シャルドネ',price:33000},
  {cat:'red',name:'Alex Gambal Bourgogne Pinot Noir La Cuvée des 2 Papis',producer:'Alex Gambal',vintage:'2019',region:'フランス ブルゴーニュ',grapes:'ピノ・ノワール',price:5500},
  {cat:'red',name:'Alex Gambal St-Aubin',producer:'Alex Gambal',vintage:'2015',region:'フランス ブルゴーニュ',grapes:'シャルドネ',price:5500},
  {cat:'red',name:'Alex Gambal Chorey-Lès-Beaune',producer:'Alex Gambal',vintage:'2014',region:'フランス ブルゴーニュ',grapes:'ピノ・ノワール',price:6500},
  {cat:'red',name:'Alex Gambal Charmes-Chambertin',producer:'Alex Gambal',vintage:'2017',region:'フランス ブルゴーニュ',grapes:'ピノ・ノワール',price:36000},
  {cat:'white',name:'エステート シャルドネ サンタ・リタ・ヒルズ',producer:'メルヴィル ワイナリー',vintage:'2018',region:'アメリカ カリフォルニア サンタ・リタ・ヒルズ',grapes:'シャルドネ',price:6500},
  {cat:'red',name:'エステート ピノ・ノワール サンタ・リタ・ヒルズ',producer:'メルヴィル ワイナリー',vintage:'2020',region:'アメリカ カリフォルニア サンタ・リタ・ヒルズ',grapes:'ピノ・ノワール',price:6500},
  {cat:'white',name:'ジアポーザ（シャルドネ）',producer:'マイケル・ポーザン ワインズ',vintage:'2018',region:'アメリカ カリフォルニア ソノマ・コースト',grapes:'シャルドネ',price:2900},
  {cat:'red',name:'ジアポーザ（カベルネ）',producer:'マイケル・ポーザン ワインズ',vintage:'2019',region:'アメリカ カリフォルニア',grapes:'カベルネ・ソーヴィニヨン・メルロ',price:2900},
  {cat:'red',name:'ナパ 1847 カベルネ・ソーヴィニヨン',producer:'マイケル・ポーザン ワインズ',vintage:'2018',region:'アメリカ カリフォルニア ナパ・ヴァレー',grapes:'カベルネ・ソーヴィニヨン・メルロ他',price:5000},
  {cat:'red',name:'ラザフォード ロード カベルネ・ソーヴィニヨン',producer:'マイケル・ポーザン ワインズ',vintage:'2018',region:'アメリカ カリフォルニア ラザフォード',grapes:'カベルネ・ソーヴィニヨン',price:5400},
  {cat:'sparkling',name:'ポップ・フリッツィ',producer:'ラルモニア',vintage:'2019',region:'イタリア ヴェネト',grapes:'ピノ・ネロ・ドゥレッラ他',price:2600},
  {cat:'white',name:'ポップ・ビアンコ',producer:'ラルモニア',vintage:'2019',region:'イタリア ヴェネト',grapes:'インクロッチョ・マンゾーニ他',price:2800},
  {cat:'red',name:'ポップ・ブリオ',producer:'ラルモニア',vintage:'2019',region:'イタリア ヴェネト',grapes:'カベルネ・フラン・バルベラ・トカイ他',price:2800},
  {cat:'sparkling',name:'a+ シック',producer:'ラルモニア',vintage:'2020',region:'イタリア ヴェネト',grapes:'シャルドネ・ドゥレッラ',price:4000},
];

// 統計情報（自動計算）
const wineStats = {
  total: wineDB.length,
  byCategory: wineDB.reduce((acc, w) => { acc[w.cat] = (acc[w.cat]||0)+1; return acc; }, {}),
  updatedAt: '2026-06-13',
};
